<?php
	function URL($percorso){print "/$percorso";}
	$titolo = (isset($titolo) && $titolo) ? $titolo : 'LugBS';
	 ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
	<TITLE><?php echo "$titolo"?></TITLE> 
	<META HTTP-EQUIV="Content-Type" content="text/html; charset=utf-8">
	<META HTTP-EQUIV="Content-Language" CONTENT="it-IT">
	<META NAME="description" CONTENT="Linux User Group di Brescia - <?php echo "$titolo";?>">
	<META NAME="viewport" CONTENT="width=device-width, initial-scale=1">
	<LINK REL="stylesheet" href="/includes/lugbs.css" type="text/css">
	<LINK REL="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="alternate" type="application/rss+xml" title="LugBS - RSS" href="http://lugbs.linux.it/rss2.0/">
</HEAD>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-3626063-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
<!-- script inutile: manca l'elemento :( -->
<!--script type="text/javascript">
function on_menu_click() {
 if (document.getElementById("testissima").style.display != "") {
  document.getElementById("testissima").style.display = "";
  } else {
  document.getElementById("testissima").style.display = "inline";
  }
}
</script-->
<!-- <a href="http://lugbs.linux.it/plugins/bond.php">select</a> -->
<BODY VLINK="blue" BGCOLOR="silver" TEXT="black" LINK="blue" ALINK="red">
<table width="100%" class="main-table">
 <tr>
  <td class="main-table">
   <table bgcolor="black" width="100%" cellspacing="3" cellpadding="0" class="border-table">
    <tr bgcolor="white">
     <td width="100%" class="border-table">
      <table cellspacing="0" width="90%" align="center" class="content-table">
       <tr>
        <td align="right" style="padding: 4">
         <h1>linux user group <span style="font-style: italic; color: red;">brescia</span></h1>
        </td>
       </tr>
       <tr>
        <td class="content-table">
         <table cellpadding="0" cellspacing="2" width="100%" bgcolor="black">
          <tr bgcolor="black">
           <td bgcolor="#eeeeff">
            <table width="100%" cellspacing="0" cellpadding="0">
             <tr>
              <td width="94" valign="bottom"><img alt="immagine del castello" src="/bs.jpg"></td>
              <td>
<div id="testata">
<TABLE width="100%" border="0" cellpadding="3" cellspacing="0">
 <tr>
  <td></td>
  <td></td>
  <td align="right">
	<form action="http://lugbs.linux.it/risultati_ricerca.php" id="cse-search-box">
		<div>
		<input type="hidden" name="cx" value="partner-pub-0142131621209311:a6xpd9-j97i" />
		<input type="hidden" name="cof" value="FORID:9" />
		<input type="hidden" name="ie" value="ISO-8859-1" />
		<input type="text" name="q" size="15" />
		<input type="submit" name="sa" value="Cerca" />
		</div>
	</form>
	<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box&amp;lang=it"></script>
  </td>
 </tr>
 <tr>
  <td colspan="2"><a href="<?php URL("");?>">Novit&agrave;</a></td>
 </tr>
 <tr>
  <td>&nbsp;</td><td>
   <small>
   <a HREF="<?php URL("novita/diario/");?>">Diario</a> :: 
   <a href="<?php URL("novita/linkconsigliati/");?>">Link&nbsp;Consigliati</a> ::
   <a href="<?php URL("novita/lugneidintorni/");?>">Lug&nbsp;nei&nbsp;Dintorni&nbsp;</a> ::
   <a href="<?php URL("rss2.0/");?>">Feed RSS2.0</a> 
   </small>
  </td>
 </tr>
 <tr>
  <td colspan="2"><a href="<?php URL("attivita/");?>">Attivit&agrave;</a></td>
 </tr>
 <tr>
  <td>&nbsp;</td><td>
   <small>
   <a href="<?php URL("attivita/mailing_list/");?>">Mailing&nbsp;List</a> ::
   <a href="<?php URL("attivita/linux_day/");?>">Linux&nbsp;Day</a> :: 
   <a href="<?php URL("attivita/didattica/");?>">Didattica&nbsp;</a> :: 
   <a href="<?php URL("attivita/eventi_locali/");?>">Eventi&nbsp;Locali</a> ::
   <a href="<?php URL("attivita/install_fest/");?>">Install&nbsp;Fest</a>
   </small>
  </td>
 </tr>
 <tr>
  <td colspan="2"><a href="<?php URL("contatti/");?>">Contatti</a></td>
 </tr>

 <tr>
  <td>&nbsp;</td><td>
   <small>
   <a HREF="<?php URL("contatti/chi_siamo/");?>">Chi&nbsp;Siamo</a> :: 
   <a HREF="<?php URL("contatti/chi_siamo/attivisti.php");?>">Attivisti</a> :: 
   <a HREF="<?php URL("contatti/faq_del_lug/");?>">FAQ</a> :: 
   <a HREF="<?php URL("contatti/ringraziamenti/");?>">Ringraziamenti</a> ::
   <a href="<?php URL("contatti/lugbs.it/");?>">LugBS.it</a>
   </small>
  </td>
 </tr>
</TABLE>
</div>

              </td>
             </tr>
            </table>
           </td>
          </tr>
         </table>
        </td>
       </tr>
       <tr>
        <td>
<!-- google_ad_section_start -->
<!-- fine dell'header -->
